sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7
    - php: hhvm

before_install:
  - composer self-update
  - composer require --no-update squizlabs/php_codesniffer:dev-master 

install:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - ./bin/phpcs
